#!/bin/sh

### Commands for Obsidian directory operations

OBSIDIAN_DIR="/Users/tanimutomo/Obsidian/tanimutomo"

# Check subcommand
case "$1" in
  cd)
    cd "$OBSIDIAN_DIR" && exec "$SHELL"
    ;;
  code)
    code "$OBSIDIAN_DIR"
    ;;
  pull)
    cd "$OBSIDIAN_DIR" && git pull origin main
    ;;
  push)
    cd "$OBSIDIAN_DIR" && git pull origin main && git add . && git commit -m "auto commit by obs" && git push origin main
    ;;
  *)
    echo "Usage: obs {cd|code}"
    echo "  cd   - Change directory to Obsidian vault"
    echo "  code - Open Obsidian vault in VSCode"
    echo "  pull - Pull origin main changes"
    echo "  push - Commit and Push changes"
    exit 1
    ;;
esac
